[default]
NAME = "default"

# Columns for db
COLS = [
    "id",
    "premium",
    "name",
    "description",
    "key_skills",
    "accept_handicapped",
    "accept_kids",
    "archived",
    "specializations",
    "professional_roles",
    "published_at",
    "created_at",
    "alternate_url",
    "billing_type.id",
    "billing_type.name",
    "experience.id",
    "experience.name",
    "schedule.id",
    "schedule.name",
    "employment.id",
    "employment.name",
    "employer.id",
    "employer.name",
    "employer.url",
    "employer.alternate_url",
    "employer.logo_urls.original",
    "employer.logo_urls.240",
    "employer.logo_urls.90",
    "employer.vacancies_url",
    "employer.trusted",
    "address.city",
    "address.street",
    "address.building",
    "address.description",
    "address.lat",
    "address.lng",
    "address.raw",
    "salary",
    "salary.currency",
    "salary.from",
    "salary.to",
    "salary.gross",
]
